### ISSUE TITLE
Extend a Useful Function - diff_index

### ISSUE THREAD

**Issue by brichard1638** [william-swl/baizer#18]
The baizer package is great! In evaluating the functionality of this package, I would like to make a recommendation. To extend the functionality of one of its functions, it would be nice if the opposite feature of diff_index were added. That is to say, instead of returning the index of character differences, what about returning the index where characters are the same?

The change literally requires a modification of one character in the diff_index function:

```
same_index = function (s1, s2, nth = 0) 
{
    if (length(s1) != 1 || length(s2) != 1) {
        stop("Need 1 length character!")
    }
    if (nchar(s1) != nchar(s2)) {
        stop("Need strings of same nchar")
    }
    diff_index <- which(unlist(stringr::str_split(s1, "")) == 
                            unlist(stringr::str_split(s2, "")))
    if (nth == 0) {
        return(diff_index)
    }
    else if (nth > 0) {
        return(diff_index[nth])
    }
}
```

I didn't modify the code for the following additional request, but would it be possible to remove the nth argument in the diff_index function, replacing it with a boolean index argument indicating whether index numbers or values are returned? It would be nice to capture either the index position or a corresponding value. Just a suggestion!

**Comment by william-swl** [comment]
Thank you for your kind feedback and helpful suggestions! 
I added the `same_index` function that returns the indices of identical characters, and expanded the `nth` argument to accept a vector of numbers as you suggested (0dbaaedcbc28e49e394d6245c5db26e0bbb2c41a).

In this commit, I also refactored these two functions so that they can support vectorized operations. To avoid confusion, I made the return value a list, even if `length(s1)` and `length(s2)` are `1`, just like what `stringr::str_split` does.

Feel free to give any comments. Thanks again!

**Comment by william-swl** [comment]
If you want the different character values but index numbers, try `fetch_char(str1, diff_index(str1, str2))` in the new version (v0.2.2).

**Comment by brichard1638** [comment]
William:::

Thank you for the follow up! It was much appreciated.

I look forward to reviewing and trying out the newly added functions in your next version of baizer.

Warm regards,

Brice Richard
Data Scientist
Washington, DC USA
________________________________
